artifact_uri: file:///home/user/PycharmProjects/mlops/plots/960470395858666371/ffb97b79803b4bf9aaca43d6cbdb0a4a/artifacts
end_time: 1736147785147
entry_point_name: ""
experiment_id: "960470395858666371"
lifecycle_stage: active
run_id: ffb97b79803b4bf9aaca43d6cbdb0a4a
run_name: bert-classifier
run_uuid: ffb97b79803b4bf9aaca43d6cbdb0a4a
source_name: ""
source_type: 4
source_version: ""
start_time: 1736147755379
status: 3
tags: []
user_id: user
